import { getContext } from "@keystone-6/core/context";
import config from "./keystone";
import * as PrismaModule from "@prisma/client";
import { GraphQLInputObjectType, GraphQLObjectType } from "graphql";

const JSONify = (data: any) => JSON.stringify(data, undefined, 4)

const common = {
  listValues: {
    cardinalDirections: [
      { value: "SE", title: "South East" },
      { value: "S", title: "South" },
      { value: "SW", title: "South West" },
      { value: "W", title: "West" },
      { value: "NW", title: "North West" },
      { value: "N", title: "North" },
      { value: "NE", title: "North East" },
      { value: "E", title: "East" },
    ],
    streetSuffixes: [
      { value: "ALY", title: "Alley" },
      { value: "ANX", title: "Annex" },
      { value: "ARC", title: "Arcade" },
      { value: "AVE", title: "Avenue" },
      { value: "AVDA", title: "Avenida" },
      { value: "BLF", title: "Bluff" },
      { value: "BLVD", title: "Boulevard" },
      { value: "BR", title: "Branch" },
      { value: "BRG", title: "Bridge" },
      { value: "BRK", title: "Brook" },
      { value: "BTM", title: "Bottom" },
      { value: "BYU", title: "Bayou" },
      { value: "CALLE", title: "Calle" },
      { value: "CAMINO", title: "Camino" },
      { value: "CIR", title: "Circle" },
      { value: "CLF", title: "Cliff" },
      { value: "CLFS", title: "Cliffs" },
      { value: "CMN", title: "Common" },
      { value: "CMNO", title: "Camino" },
      { value: "CORS", title: "Corner" },
      { value: "COURT", title: "Court" },
      { value: "CP", title: "Camp" },
      { value: "CPE", title: "Cape" },
      { value: "CRK", title: "Creek" },
      { value: "CROSSING", title: "Crossing" },
      { value: "CSWY", title: "Causeway" },
      { value: "CT", title: "Court" },
      { value: "CTS", title: "Courts" },
      { value: "CV", title: "Cove" },
      { value: "CYN", title: "Canyon" },
      { value: "DL", title: "Dale" },
      { value: "DM", title: "Dam" },
      { value: "DR", title: "Drive" },
      { value: "DRS", title: "Drives" },
      { value: "ENT", title: "Entrance" },
      { value: "EST", title: "Estate" },
      { value: "ESTS", title: "Estates" },
      { value: "EXPY", title: "Expressway" },
      { value: "EXT", title: "Extension" },
      { value: "EXTS", title: "Extensions" },
      { value: "FLD", title: "Field" },
      { value: "FLDS", title: "Fields" },
      { value: "FLS", title: "Falls" },
      { value: "FLT", title: "Flat" },
      { value: "FM", title: "Farm" },
      { value: "FRD", title: "Ford" },
      { value: "FRG", title: "Forge" },
      { value: "FRK", title: "Fork" },
      { value: "FRKS", title: "Forks" },
      { value: "FRST", title: "Forest" },
      { value: "FRY", title: "Ferry" },
      { value: "FWY", title: "Freeway" },
      { value: "GDNS", title: "Gardens" },
      { value: "GLN", title: "Glen" },
      { value: "GRN", title: "Green" },
      { value: "GRNS", title: "Greens" },
      { value: "GRVS", title: "Grove" },
      { value: "GTWY", title: "Gateway" },
      { value: "HBR", title: "Harbor" },
      { value: "HVN", title: "Haven" },
      { value: "HWY", title: "Highway" },
      { value: "INLT", title: "Inlet" },
      { value: "IS", title: "Island" },
      { value: "ISLE", title: "Isle" },
      { value: "JCT", title: "Junction" },
      { value: "KNL", title: "Knoll" },
      { value: "KNLS", title: "Knolls" },
      { value: "KY", title: "Key" },
      { value: "KYS", title: "Keys" },
      { value: "LCK", title: "Lock" },
      { value: "LCKS", title: "Locks" },
      { value: "LDG", title: "Lodge" },
      { value: "LF", title: "Loaf" },
      { value: "LGT", title: "Light" },
      { value: "LGTS", title: "Lights" },
      { value: "LNDG", title: "Landing" },
      { value: "LN", title: "Lane" },
      { value: "LKS", title: "Lakes" },
      { value: "MNR", title: "Manor" },
      { value: "MDW", title: "Meadow" },
      { value: "MDWS", title: "Meadows" },
      { value: "MEWS", title: "Mews" },
      { value: "MLS", title: "Mills" },
      { value: "MSN", title: "Mission" },
      { value: "MT", title: "Mount" },
      { value: "MTN", title: "Mountain" },
      { value: "MTNS", title: "Mountains" },
      { value: "MTWY", title: "Motorway" },
      { value: "NCK", title: "Neck" },
      { value: "ORCH", title: "Orchard" },
      { value: "PARK", title: "Park" },
      { value: "PARKWAY", title: "Parkway" },
      { value: "PASAJE", title: "Pasaje" },
      { value: "PASEO", title: "Paseo" },
      { value: "PATH", title: "Path" },
      { value: "PH", title: "Path" },
      { value: "PIKE", title: "Pike" },
      { value: "PL", title: "Place" },
      { value: "PLN", title: "Plain" },
      { value: "PLNS", title: "Plains" },
      { value: "PLZ", title: "Plaza" },
      { value: "PNES", title: "Pines" },
      { value: "PRT", title: "Port" },
      { value: "PTS", title: "Points" },
      { value: "RADL", title: "Radial" },
      { value: "RAMP", title: "Ramp" },
      { value: "RD", title: "Road" },
      { value: "RDG", title: "Ridge" },
      { value: "RDGS", title: "Ridges" },
      { value: "RIV", title: "River" },
      { value: "RNCH", title: "Ranch" },
      { value: "RPD", title: "Rapid" },
      { value: "RPDS", title: "Rapids" },
      { value: "RST", title: "Rest" },
      { value: "ROUTE", title: "Route" },
      { value: "ROW", title: "Row" },
      { value: "RUE", title: "Rue" },
      { value: "RUN", title: "Run" },
      { value: "SHL", title: "Shoal" },
      { value: "SHLS", title: "Shoals" },
      { value: "SHR", title: "Shore" },
      { value: "SHRS", title: "Shores" },
      { value: "SKWY", title: "Skyway" },
      { value: "SPG", title: "Spring" },
      { value: "SPGS", title: "Springs" },
      { value: "SPUR", title: "Spur" },
      { value: "SQ", title: "Square" },
      { value: "SQS", title: "Squares" },
      { value: "STA", title: "Station" },
      { value: "STRA", title: "Stravenue" },
      { value: "STRM", title: "Stream" },
      { value: "ST", title: "Street" },
      { value: "STS", title: "Streets" },
      { value: "TER", title: "Terrace" },
      { value: "TPKE", title: "Turnpike" },
      { value: "TRCE", title: "Trace" },
      { value: "TRAK", title: "Track" },
      { value: "TRL", title: "Trail" },
      { value: "TRWY", title: "Throughway" },
      { value: "TUNL", title: "Tunnel" },
      { value: "US", title: "United States" },
      { value: "UN", title: "Union" },
      { value: "VALLEY", title: "Valley" },
      { value: "VIADUCT", title: "Viaduct" },
      { value: "VL", title: "Ville" },
      { value: "VW", title: "View" },
      { value: "VWS", title: "Views" },
      { value: "VLG", title: "Village" },
    ],
    states: [
      { value: "AK", title: "Alaska" },
      { value: "AL", title: "Alabama" },
      { value: "AR", title: "Arkansas" },
      { value: "AZ", title: "Arizona" },
      { value: "CA", title: "California" },
      { value: "CO", title: "Colorado" },
      { value: "CT", title: "Connecticut" },
      { value: "DC", title: "District of Columbia" },
      { value: "DE", title: "Delaware" },
      { value: "FL", title: "Florida" },
      { value: "GA", title: "Georgia" },
      { value: "HI", title: "Hawaii" },
      { value: "IA", title: "Iowa" },
      { value: "ID", title: "Idaho" },
      { value: "IL", title: "Illinois" },
      { value: "IN", title: "Indiana" },
      { value: "KS", title: "Kansas" },
      { value: "KY", title: "Kentucky" },
      { value: "LA", title: "Louisiana" },
      { value: "MA", title: "Massachusetts" },
      { value: "MD", title: "Maryland" },
      { value: "ME", title: "Maine" },
      { value: "MI", title: "Michigan" },
      { value: "MN", title: "Minnesota" },
      { value: "MO", title: "Missouri" },
      { value: "MS", title: "Mississippi" },
      { value: "MT", title: "Montana" },
      { value: "NC", title: "North Carolina" },
      { value: "ND", title: "North Dakota" },
      { value: "NE", title: "Nebraska" },
      { value: "NH", title: "New Hampshire" },
      { value: "NJ", title: "New Jersey" },
      { value: "NM", title: "New Mexico" },
      { value: "NV", title: "Nevada" },
      { value: "NY", title: "New York" },
      { value: "OH", title: "Ohio" },
      { value: "OK", title: "Oklahoma" },
      { value: "OR", title: "Oregon" },
      { value: "PA", title: "Pennsylvania" },
      { value: "RI", title: "Rhode Island" },
      { value: "SC", title: "South Carolina" },
      { value: "SD", title: "South Dakota" },
      { value: "TN", title: "Tennessee" },
      { value: "TX", title: "Texas" },
      { value: "UT", title: "Utah" },
      { value: "VA", title: "Virginia" },
      { value: "VT", title: "Vermont" },
      { value: "WA", title: "Washington" },
      { value: "WI", title: "Wisconsin" },
      { value: "WV", title: "West Virginia" },
      { value: "WY", title: "Wyoming" },
    ],
  },
};

const filters = {
  address: {
    primaryNumber: {
      label: "Address: Primary Number",
      type: "text",
    },
    streetPredirection: {
      label: "Address: Pre-Direction",
      type: "select",
      valueSources: ["value"],
      fieldSettings: {
        listValues: common.listValues.cardinalDirections,
      },
    },
    streetName: {
      label: "Address: Street Name",
      type: "text",
    },
    streetSuffix: {
      label: "Address: Street Suffix",
      type: "select",
      valueSources: ["value"],
      fieldSettings: {
        listValues: common.listValues.streetSuffixes,
      },
    },
    streetPostdirection: {
      label: "Address: Post-Direction",
      type: "select",
      valueSources: ["value"],
      fieldSettings: {
        listValues: common.listValues.cardinalDirections,
      },
    },
    secondaryDesignator: {
      label: "Address: Secondary Designator",
      type: "text",
    },
    secondaryNumber: {
      label: "Address: Secondary Number",
      type: "text",
    },
    city: {
      label: "Address: City",
      type: "text",
    },
    state: {
      label: "Address: State",
      type: "select",
      valueSources: ["value"],
      fieldSettings: {
        listValues: common.listValues.states,
      },
    },
    zipCode: {
      label: "Address: Zip Code",
      type: "text",
    },
    plus4Code: {
      label: "Address: +4 Code",
      type: "text",
    },
    latitude: {
      label: "Geography: Latitude",
      type: "number",
    },
    longitude: {
      label: "Geography: Longitude",
      type: "number",
    },
    h3_index: {
      label: "Geography: H3 (7)",
      type: "text",
    },
  },
};

const seed_data: { [listKey: string]: any } = {
  Publisher: [
    { title: "Meta" },
    { title: "OneView" },
    { title: "Xandr" },
  ],
  DataType: [
    { title: "Addresses" },
    { title: "Device IDs" },
    { title: "Polygons" },
  ],
  DataSource: [
    {
      title: "Attom's Estated Data",
      dataType: { connect: { title: "Addresses" } },
      filtering: JSONify({
        ID: {
          label: "ID",
          type: "text",
        },
        FIPS: {
          label: "FIPS",
          type: "text",
        },
        datePublished: {
          label: "Meta: Date Published",
          type: "datetime",
        },
        ...filters.address,
      }),
    },
    {
      title: "DeepSync's Movers Data",
      dataType: { connect: { title: "Addresses" } },
      filtering: JSONify({
        ...filters.address,
        date: {
          label: "Meta: Date Published",
          type: "datetime",
        },
        homeOwnership: {
          label: "Demographics: Home Ownership",
          type: "select",
          valueSources: ["value"],
          fieldSettings: {
            listValues: [
              { value: "None" },
              { value: "HomeOwner" },
              { value: "ProbableHomeOwner" },
              { value: "ProbableRenter" },
              { value: "Renter" },
            ],
          },
        },
        addressType: {
          label: "Demographics: Address Type",
          type: "select",
          valueSources: ["value"],
          fieldSettings: {
            listValues: [
              { value: "None" },
              { value: "Highrise" },
              { value: "SingleFamily" },
            ],
          },
        },
        estimatedIncome: {
          label: "Demographics: Estimated Income",
          type: "number",
        },
        estimatedHomeValue: {
          label: "Demographics: Estimated Home Value",
          type: "number",
        },
        estimatedAge: {
          label: "Demographics: Estimated Age",
          type: "number",
        },
      }),
    },
    {
      title: "Esquire's Audience Data",
      dataType: { connect: { title: "Device IDs" } },
      filtering: JSONify({
        id: {
          label: "ID",
          type: "text",
        },
        tags: {
          label: "Tags",
          type: "text",
        },
      }),
    },
    {
      title: "Esquire's GeoFrame Data",
      dataType: { connect: { title: "Polygons" } },
      filtering: JSONify({
        id: {
          label: "ID",
          type: "text",
        },
        esqid: {
          label: "ESQ ID (Legacy)",
          type: "text",
        },
      }),
    },
    {
      title: "Esquire's Sales Data",
      dataType: { connect: { title: "Addresses" } },
      filtering: JSONify({
        ...filters.address,
        client: {
          label: "Client",
          type: "text",
        },
        date: {
          label: "Transaction Date",
          type: "datetime",
        },
      }),
    },
    {
      title: "FourSquare's POI Data",
      dataType: { connect: { title: "Addresses" } },
      filtering: JSONify({
        ...filters.address,
      }),
    },
    {
      title: "OpenStreetMaps' Building Footprints",
      dataType: { connect: { title: "Polygons" } },
      filtering: JSONify({
        ...filters.address,
      }),
    },
  ],
  Audience: [
    {
      tags: "New Movers,California Closets,Atlanta",
      rebuildFrequency: 1,
      rebuildUnit: "weeks",
      dataSource: { connect: { title: "DeepSync's Movers Data" } },
      dataFilter: JSONify({
        and: [
          { ">=": [{ var: "date" }, { date_add: [{ now: [] }, -9, "month"] }] },
          {
            in: [
              { var: "zipCode" },
              [
                "30004",
                "30005",
                "30009",
                "30022",
                "30024",
                "30030",
                "30040",
                "30041",
                "30062",
                "30066",
                "30067",
                "30068",
                "30075",
                "30076",
                "30092",
                "30097",
                "30269",
                "30305",
                "30306",
                "30307",
                "30308",
                "30309",
                "30319",
                "30327",
                "30328",
                "30338",
                "30339",
                "30342",
                "30345",
                "30350",
                "30363",
                "35213",
                "35223",
                "35242",
                "35243",
                "35244",
                "35406",
                "28801",
                "28803",
                "28804",
                "28805",
                "28806",
                "29607",
                "29609",
                "29642",
                "29644",
                "29650",
                "29651",
                "29687",
                "29690",
                "31901",
                "31902",
                "31903",
                "31904",
                "31906",
                "31907",
                "31908",
                "31909",
                "31914",
                "31917",
                "31993",
                "31997",
                "31998",
              ],
            ],
          },
          { ">=": [{ var: "estimatedHomeValue" }, 600000] },
        ],
      }),
    },
    {
      tags: "Venue Replay,California Closets,Atlanta",
      rebuildFrequency: 1,
      rebuildUnit: "weeks",
      dataSource: { connect: { title: "Esquire's GeoFrame Data" } },
      dataFilter: JSONify({
        and: [
          {
            in: [
              { var: "esqid" },
              [
                "EF~06491",
                "EF~06492",
                "EF~06993",
                "EF~06994",
                "EF~32577",
                "EF~32578",
                "EF~32934",
                "EF~32935",
                "EF~32936",
                "EF~32937",
                "EF~32938",
                "EF~32939",
                "EF~32940",
                "EF~32941",
              ],
            ],
          },
        ],
      }),
      processes: {
        create: [
          {
            outputType: { connect: { title: "Device IDs" } },
            sort: 0,
            customCoding: JSONify({
              request: {
                dateStart: { date_add: [{ now: [] }, -6, "month"] },
                dateEnd: { date_add: [{ now: [] }, -2, "days"] },
              },
            }),
          },
          {
            outputType: { connect: { title: "Addresses" } },
            sort: 1,
            customCoding: JSONify({
              filter: {
                and: [
                  {
                    in: [
                      { var: "zipCode" },
                      [
                        "30004",
                        "30005",
                        "30009",
                        "30022",
                        "30024",
                        "30030",
                        "30040",
                        "30041",
                        "30062",
                        "30066",
                        "30067",
                        "30068",
                        "30075",
                        "30076",
                        "30092",
                        "30097",
                        "30269",
                        "30305",
                        "30306",
                        "30307",
                        "30308",
                        "30309",
                        "30319",
                        "30327",
                        "30328",
                        "30338",
                        "30339",
                        "30342",
                        "30345",
                        "30350",
                        "30363",
                        "35213",
                        "35223",
                        "35242",
                        "35243",
                        "35244",
                        "35406",
                        "28801",
                        "28803",
                        "28804",
                        "28805",
                        "28806",
                        "29607",
                        "29609",
                        "29642",
                        "29644",
                        "29650",
                        "29651",
                        "29687",
                        "29690",
                        "31901",
                        "31902",
                        "31903",
                        "31904",
                        "31906",
                        "31907",
                        "31908",
                        "31909",
                        "31914",
                        "31917",
                        "31993",
                        "31997",
                        "31998",
                      ],
                    ],
                  },
                ],
              },
            }),
          },
          {
            outputType: { connect: { title: "Device IDs" } },
            sort: 2,
            customCoding: JSONify({
              demographics: {
                filter: {
                  and: [{ ">=": [{ var: "estimatedHomeValue" }, 600000] }],
                },
              },
            }),
          },
        ],
      },
    },
    {
      tags: "Friends & Family,AFW,Ashley,Arizona",
      rebuildFrequency: 1,
      rebuildUnit: "weeks",
      dataSource: { connect: { title: "Esquire's Sales Data" } },
      dataFilter: JSONify({
        and: [
          { "==": [{ var: "client" }, "AFW???"] },
          { ">=": [{ var: "date" }, { date_add: [{ now: [] }, -45, "days"] }] },
          { "==": [{ var: "state" }, "AZ"] },
        ],
      }),
      processes: {
        create: [
          {
            outputType: { connect: { title: "Polygons" } },
            sort: 0,
            customCoding: JSONify({
              request: {
                dateStart: { date_add: [{ now: [] }, -6, "month"] },
                dateEnd: { date_add: [{ now: [] }, -2, "days"] },
              },
            }),
          },
          {
            outputType: { connect: { title: "Device IDs" } },
            sort: 1,
            customCoding: JSONify({
              observation: {
                filter: {
                  and: [{ "<": [{ reduce: { filter: [] } }, 20] }],
                },
              },
            }),
          },
        ],
      },
    },
    {
      tags: "Past Customer,Skandinavia",
      rebuildFrequency: 1,
      rebuildUnit: "weeks",
      dataSource: { connect: { title: "Esquire's Sales Data" } },
      dataFilter: JSONify({
        and: [
          { "==": [{ var: "client" }, "Skandinavia???"] },
          { ">=": [{ var: "date" }, { date_add: [{ now: [] }, -90, "days"] }] },
          { "==": [{ var: "state" }, "TX"] },
        ],
      }),
    },
    {
      tags: "Custom Demographic,Agren,NEAG",
      rebuildFrequency: 1,
      rebuildUnit: "months",
      dataSource: { connect: { title: "Attom's Estated Data" } },
      dataFilter: JSONify({
        and: [
          {
            in: [
              { var: "zipCode" },
              [
                "04210",
                "04212",
                "04211",
                "04241",
                "04243",
                "04240",
                "04223",
                "04230",
                "04250",
                "04258",
                "04236",
                "04274",
                "04280",
                "04256",
                "04288",
                "04260",
                "04252",
                "04222",
                "04238",
                "04291",
                "04282",
                "04287",
                "04069",
                "04270",
                "04259",
                "04263",
                "04039",
                "04350",
                "04086",
                "04097",
                "04265",
                "04015",
                "04032",
                "04281",
                "04034",
                "04033",
                "04266",
                "04071",
                "04220",
                "04271",
                "04011",
                "04008",
                "04284",
                "04078",
                "04357",
                "04086",
                "04011",
                "04287",
                "04252",
                "04008",
                "04222",
                "04250",
                "04579",
                "04032",
                "04530",
                "04033",
                "04034",
                "04280",
                "04357",
                "04079",
                "04069",
                "04240",
                "04078",
                "04342",
                "04350",
                "04013",
                "04578",
                "04066",
                "04565",
                "04562",
                "04571",
                "04548",
                "04210",
                "04241",
                "04243",
                "04549",
                "04097",
                "04212",
                "04211",
                "04223",
                "04003",
                "04096",
                "04260",
                "04345",
                "04359",
                "04537",
                "04556",
                "04259",
                "04236",
                "04575",
                "04576",
                "04535",
                "04017",
                "04538",
                "04110",
                "04230",
                "04021",
                "04570",
                "04039",
                "04573",
                "04268",
                "04267",
                "04271",
                "04255",
                "04281",
                "04289",
                "04088",
                "04057",
                "04040",
                "04270",
                "04238",
                "04219",
                "04292",
                "04288",
                "04016",
                "04231",
                "04256",
                "04220",
                "04051",
                "04258",
                "04291",
                "04009",
                "04217",
                "04286",
                "04274",
                "04055",
                "04230",
                "04037",
                "04282",
                "04290",
                "04015",
                "04266",
                "04237",
                "04022",
                "04221",
                "04101",
                "04104",
                "04122",
                "04112",
                "04116",
                "04123",
                "04124",
                "04102",
                "04103",
                "04109",
                "04106",
                "04108",
                "04107",
                "04092",
                "04098",
                "04050",
                "04105",
                "04070",
                "04074",
                "04110",
                "04019",
                "04017",
                "04021",
                "04082",
                "04096",
                "04038",
                "04064",
                "04062",
                "04063",
                "04072",
                "04078",
                "04013",
                "04097",
                "04093",
                "04003",
                "04004",
                "04007",
                "04006",
                "04033",
                "04034",
                "04005",
                "04039",
                "04084",
                "04032",
                "04066",
                "04069",
                "04079",
                "04042",
                "04077",
                "04085",
                "04072",
                "04007",
                "04005",
                "04064",
                "04063",
                "04074",
                "04004",
                "04070",
                "04093",
                "04046",
                "04006",
                "04042",
                "04106",
                "04094",
                "04098",
                "04043",
                "04014",
                "04002",
                "04107",
                "04102",
                "04092",
                "04038",
                "04030",
                "04101",
                "04112",
                "04116",
                "04122",
                "04104",
                "04124",
                "04123",
                "04103",
                "04082",
                "04087",
                "04109",
                "04061",
                "04108",
                "04073",
                "04090",
                "04084",
                "04105",
                "04085",
                "04062",
                "04049",
                "04083",
                "04050",
                "04076",
                "04048",
                "04054",
                "04009",
                "04022",
                "04057",
                "04040",
                "04055",
                "04037",
                "04010",
                "04029",
                "04016",
                "04088",
                "04041",
                "04267",
                "04015",
                "04270",
                "04051",
                "04091",
                "04024",
                "04291",
                "03813",
                "04071",
                "04268",
                "04077",
                "04068",
                "03860",
                "04231",
                "03832",
                "04256",
                "04274",
                "03847",
                "04020",
                "03849",
                "04085",
                "04281",
                "03845",
                "04271",
                "04255",
              ],
            ],
          },
        ],
      }),
      processes: {
        create: [
          {
            outputType: { connect: { title: "Device IDs" } },
            sort: 0,
            customCoding: JSONify({
              request: {
                dateStart: { date_add: [{ now: [] }, -6, "month"] },
                dateEnd: { date_add: [{ now: [] }, -2, "days"] },
              },
              demographics: {
                filter: {
                  and: [
                    { "==": [{ var: "Home Owner" }, true] },
                    { "==": [{ var: "Gourmet Cooking" }, true] },
                    { "==": [{ var: "Home Furnishings" }, true] },
                    { "==": [{ var: "Home Gardening" }, true] },
                    { "==": [{ var: "Home Improvement" }, true] },
                    { ">": [{ var: "Financial" }, 100000] },
                  ],
                },
              },
            }),
          },
        ],
      },
    },
    {
      tags: "Digital Neighbor,RTB,KY,Louisville",
      rebuildFrequency: 1,
      rebuildUnit: "weeks",
      dataSource: { connect: { title: "Esquire's Sales Data" } },
      dataFilter: JSONify({
        and: [
          { "==": [{ var: "client" }, "RTB???"] },
          { ">=": [{ var: "date" }, { date_add: [{ now: [] }, -45, "days"] }] },
          { "==": [{ var: "state" }, "KY"] },
        ],
      }),
    },
  ],
};

async function main() {
  const context = getContext(config, PrismaModule);

  console.log(`🌱 Inserting seed data`);
  for (const [listKey, items] of Object.entries(seed_data)) {
    const gqlt = context.graphql.schema.getTypeMap()[
      listKey
    ] as GraphQLObjectType;
    const uniqueFields = Object.keys(
      (
        context.graphql.schema.getTypeMap()[
          listKey + "WhereUniqueInput"
        ] as GraphQLInputObjectType
      ).getFields()
    ).filter((key) => key !== "id");
    for (const data of items) {
      const whereClause: { [key: string]: any } = {};
      uniqueFields.forEach((fieldName: string) => {
        if (data.hasOwnProperty(fieldName)) {
          whereClause[fieldName] = (data as any)[fieldName];
        }
      });
      const existingItem = await context.db[listKey].findOne({
        where: whereClause,
      });
      if (!existingItem) {
        try {
          await context.db[listKey].createOne({
            data,
          });
          console.log(
            `Created ${listKey} record with unique fields: ${JSONify(
              whereClause
            )}`
          );
        } catch (error) {
          console.warn(
            `Could not create ${listKey} record with unique fields: ${JSONify(
              whereClause
            )}`
          );
        }
      } else {
        console.log(
          `Updating existing ${listKey} record with unique fields: ${JSONify(
            whereClause
          )}`
        );
        await context.db[listKey].updateOne({
          where: { id: existingItem.id },
          data: data,
        });
      }
    }
  }
  console.log(`✅ Seed data inserted`);
}

main();
