import filters from "./filters";

const JSONify = (data: any) => JSON.stringify(data, undefined, 4);

const seed_data: { [listKey: string]: any } = {
  Role: [{ title: "Administrator" }],
  User: [
    {
      name: "Admin",
      email: "admin@site.com",
      password: "password",
      role: () => ({ connect: { id: seed_data.Role[0].id } }),
    },
    { name: "Test User 1", email: "test1@site.com", password: "password" },
    { name: "Test User 2", email: "test2@site.com", password: "password" },
  ],
  Tag: [
    { title: "New Movers" },
    { title: "Past Customer" },
    { title: "Venue Replay" },
    { title: "Friends & Family" },
    { title: "Custom Demographic" },
    { title: "Digital Neighbor" },
    { title: "Atlanta" },
    { title: "Arizona" },
    { title: "Kentuky" },
    { title: "Louisville" },
  ],
  Advertiser: [
    {
      title: "California Closets",
      users: () => ({ connect: [{ id: seed_data.User[1].id }] }),
    },
    {
      title: "American Furniture Warehouse",
      users: () => ({ connect: [{ id: seed_data.User[1].id }] }),
    },
    {
      title: "Skandinavia",
      users: () => ({ connect: [{ id: seed_data.User[1].id }] }),
    },
    {
      title: "Agren",
      users: () => ({ connect: [{ id: seed_data.User[2].id }] }),
    },
    {
      title: "Ashley",
      users: () => ({ connect: [{ id: seed_data.User[1].id }] }),
    },
    {
      title: "NEAG",
      users: () => ({ connect: [{ id: seed_data.User[2].id }] }),
    },
    {
      title: "Relax the Back",
      users: () => ({ connect: [{ id: seed_data.User[2].id }] }),
    },
  ],
  Publisher: [{ title: "Meta" }, { title: "OneView" }, { title: "Xandr" }],
  DataType: [
    { title: "Addresses" },
    { title: "Device IDs" },
    { title: "Polygons" },
  ],
  DataSource: [
    {
      title: "Attom's Estated Data",
      dataType: () => ({ connect: { id: seed_data.DataType[0].id } }),
      filtering: JSONify({
        ID: {
          label: "ID",
          type: "text",
        },
        FIPS: {
          label: "FIPS",
          type: "text",
        },
        datePublished: {
          label: "Meta: Date Published",
          type: "datetime",
        },
        ...filters.address,
      }),
    },
    {
      title: "DeepSync's Movers Data",
      dataType: () => ({ connect: { id: seed_data.DataType[0].id } }),
      filtering: JSONify({
        ...filters.address,
        date: {
          label: "Meta: Date Published",
          type: "datetime",
        },
        homeOwnership: {
          label: "Demographics: Home Ownership",
          type: "select",
          valueSources: ["value"],
          fieldSettings: {
            listValues: [
              { value: "None" },
              { value: "HomeOwner" },
              { value: "ProbableHomeOwner" },
              { value: "ProbableRenter" },
              { value: "Renter" },
            ],
          },
        },
        addressType: {
          label: "Demographics: Address Type",
          type: "select",
          valueSources: ["value"],
          fieldSettings: {
            listValues: [
              { value: "None" },
              { value: "Highrise" },
              { value: "SingleFamily" },
            ],
          },
        },
        estimatedIncome: {
          label: "Demographics: Estimated Income",
          type: "number",
        },
        estimatedHomeValue: {
          label: "Demographics: Estimated Home Value",
          type: "number",
        },
        estimatedAge: {
          label: "Demographics: Estimated Age",
          type: "number",
        },
      }),
    },
    {
      title: "Esquire's Audience Data",
      dataType: () => ({ connect: { id: seed_data.DataType[1].id } }),
      filtering: JSONify({
        id: {
          label: "ID",
          type: "text",
        },
        tags: {
          label: "Tags",
          type: "text",
        },
      }),
    },
    {
      title: "Esquire's GeoFrame Data",
      dataType: () => ({ connect: { id: seed_data.DataType[2].id } }),
      filtering: JSONify({
        id: {
          label: "ID",
          type: "text",
        },
        esqid: {
          label: "ESQ ID (Legacy)",
          type: "text",
        },
      }),
    },
    {
      title: "Esquire's Sales Data",
      dataType: () => ({ connect: { id: seed_data.DataType[0].id } }),
      filtering: JSONify({
        ...filters.address,
        client: {
          label: "Client",
          type: "text",
        },
        date: {
          label: "Transaction Date",
          type: "datetime",
        },
      }),
    },
    {
      title: "FourSquare's POI Data",
      dataType: () => ({ connect: { id: seed_data.DataType[0].id } }),
      filtering: JSONify({
        ...filters.address,
      }),
    },
    {
      title: "OpenStreetMaps' Building Footprints",
      dataType: () => ({ connect: { id: seed_data.DataType[2].id } }),
      filtering: JSONify({
        ...filters.address,
      }),
    },
  ],
  Audience: [
    {
      advertisers: () => ({ connect: [{ id: seed_data.Advertiser[0].id }] }),
      tags: () => ({
        connect: [{ id: seed_data.Tag[0].id }, { id: seed_data.Tag[6].id }],
      }),
      rebuildFrequency: 1,
      rebuildUnit: "weeks",
      dataSource: () => ({ connect: { id: seed_data.DataSource[1].id } }),
      dataFilter: JSONify({
        and: [
          { ">=": [{ var: "date" }, { date_add: [{ now: [] }, -9, "month"] }] },
          {
            in: [
              { var: "zipCode" },
              [
                "30004",
                "30005",
                "30009",
                "30022",
                "30024",
                "30030",
                "30040",
                "30041",
                "30062",
                "30066",
                "30067",
                "30068",
                "30075",
                "30076",
                "30092",
                "30097",
                "30269",
                "30305",
                "30306",
                "30307",
                "30308",
                "30309",
                "30319",
                "30327",
                "30328",
                "30338",
                "30339",
                "30342",
                "30345",
                "30350",
                "30363",
                "35213",
                "35223",
                "35242",
                "35243",
                "35244",
                "35406",
                "28801",
                "28803",
                "28804",
                "28805",
                "28806",
                "29607",
                "29609",
                "29642",
                "29644",
                "29650",
                "29651",
                "29687",
                "29690",
                "31901",
                "31902",
                "31903",
                "31904",
                "31906",
                "31907",
                "31908",
                "31909",
                "31914",
                "31917",
                "31993",
                "31997",
                "31998",
              ],
            ],
          },
          { ">=": [{ var: "estimatedHomeValue" }, 600000] },
        ],
      }),
    },
    {
      advertisers: () => ({ connect: [{ id: seed_data.Advertiser[2].id }] }),
      tags: () => ({
        connect: [{ id: seed_data.Tag[1].id }],
      }),
      rebuildFrequency: 1,
      rebuildUnit: "weeks",
      dataSource: () => ({ connect: { id: seed_data.DataSource[4].id } }),
      dataFilter: JSONify({
        and: [
          { "==": [{ var: "client" }, "Skandinavia???"] },
          { ">=": [{ var: "date" }, { date_add: [{ now: [] }, -90, "days"] }] },
          { "==": [{ var: "state" }, "TX"] },
        ],
      }),
    },
    {
      advertisers: () => ({ connect: [{ id: seed_data.Advertiser[6].id }] }),
      tags: () => ({
        connect: [
          { id: seed_data.Tag[5].id },
          { id: seed_data.Tag[8].id },
          { id: seed_data.Tag[9].id },
        ],
      }),
      rebuildFrequency: 1,
      rebuildUnit: "weeks",
      dataSource: () => ({ connect: { id: seed_data.DataSource[4].id } }),
      dataFilter: JSONify({
        and: [
          { "==": [{ var: "client" }, "RTB???"] },
          { ">=": [{ var: "date" }, { date_add: [{ now: [] }, -45, "days"] }] },
          { "==": [{ var: "state" }, "KY"] },
        ],
      }),
    },
    {
      advertisers: () => ({ connect: [{ id: seed_data.Advertiser[0].id }] }),
      tags: () => ({
        connect: [{ id: seed_data.Tag[2].id }, { id: seed_data.Tag[6].id }],
      }),
      rebuildFrequency: 1,
      rebuildUnit: "weeks",
      dataSource: () => ({ connect: { id: seed_data.DataSource[3].id } }),
      dataFilter: JSONify({
        and: [
          {
            in: [
              { var: "esqid" },
              [
                "EF~06491",
                "EF~06492",
                "EF~06993",
                "EF~06994",
                "EF~32577",
                "EF~32578",
                "EF~32934",
                "EF~32935",
                "EF~32936",
                "EF~32937",
                "EF~32938",
                "EF~32939",
                "EF~32940",
                "EF~32941",
              ],
            ],
          },
        ],
      }),
    },
    {
      advertisers: () => ({
        connect: [
          { id: seed_data.Advertiser[1].id },
          { id: seed_data.Advertiser[4].id },
        ],
      }),
      tags: () => ({
        connect: [{ id: seed_data.Tag[3].id }, { id: seed_data.Tag[7].id }],
      }),
      rebuildFrequency: 1,
      rebuildUnit: "weeks",
      dataSource: () => ({ connect: { id: seed_data.DataSource[4].id } }),
      dataFilter: JSONify({
        and: [
          { "==": [{ var: "client" }, "AFW???"] },
          { ">=": [{ var: "date" }, { date_add: [{ now: [] }, -45, "days"] }] },
          { "==": [{ var: "state" }, "AZ"] },
        ],
      }),
    },
    {
      advertisers: () => ({
        connect: [
          { id: seed_data.Advertiser[3].id },
          { id: seed_data.Advertiser[5].id },
        ],
      }),
      tags: () => ({
        connect: [{ id: seed_data.Tag[4].id }],
      }),
      rebuildFrequency: 1,
      rebuildUnit: "months",
      dataSource: () => ({ connect: { id: seed_data.DataSource[0].id } }),
      dataFilter: JSONify({
        and: [
          {
            in: [
              { var: "zipCode" },
              [
                "04210",
                "04212",
                "04211",
                "04241",
                "04243",
                "04240",
                "04223",
                "04230",
                "04250",
                "04258",
                "04236",
                "04274",
                "04280",
                "04256",
                "04288",
                "04260",
                "04252",
                "04222",
                "04238",
                "04291",
                "04282",
                "04287",
                "04069",
                "04270",
                "04259",
                "04263",
                "04039",
                "04350",
                "04086",
                "04097",
                "04265",
                "04015",
                "04032",
                "04281",
                "04034",
                "04033",
                "04266",
                "04071",
                "04220",
                "04271",
                "04011",
                "04008",
                "04284",
                "04078",
                "04357",
                "04086",
                "04011",
                "04287",
                "04252",
                "04008",
                "04222",
                "04250",
                "04579",
                "04032",
                "04530",
                "04033",
                "04034",
                "04280",
                "04357",
                "04079",
                "04069",
                "04240",
                "04078",
                "04342",
                "04350",
                "04013",
                "04578",
                "04066",
                "04565",
                "04562",
                "04571",
                "04548",
                "04210",
                "04241",
                "04243",
                "04549",
                "04097",
                "04212",
                "04211",
                "04223",
                "04003",
                "04096",
                "04260",
                "04345",
                "04359",
                "04537",
                "04556",
                "04259",
                "04236",
                "04575",
                "04576",
                "04535",
                "04017",
                "04538",
                "04110",
                "04230",
                "04021",
                "04570",
                "04039",
                "04573",
                "04268",
                "04267",
                "04271",
                "04255",
                "04281",
                "04289",
                "04088",
                "04057",
                "04040",
                "04270",
                "04238",
                "04219",
                "04292",
                "04288",
                "04016",
                "04231",
                "04256",
                "04220",
                "04051",
                "04258",
                "04291",
                "04009",
                "04217",
                "04286",
                "04274",
                "04055",
                "04230",
                "04037",
                "04282",
                "04290",
                "04015",
                "04266",
                "04237",
                "04022",
                "04221",
                "04101",
                "04104",
                "04122",
                "04112",
                "04116",
                "04123",
                "04124",
                "04102",
                "04103",
                "04109",
                "04106",
                "04108",
                "04107",
                "04092",
                "04098",
                "04050",
                "04105",
                "04070",
                "04074",
                "04110",
                "04019",
                "04017",
                "04021",
                "04082",
                "04096",
                "04038",
                "04064",
                "04062",
                "04063",
                "04072",
                "04078",
                "04013",
                "04097",
                "04093",
                "04003",
                "04004",
                "04007",
                "04006",
                "04033",
                "04034",
                "04005",
                "04039",
                "04084",
                "04032",
                "04066",
                "04069",
                "04079",
                "04042",
                "04077",
                "04085",
                "04072",
                "04007",
                "04005",
                "04064",
                "04063",
                "04074",
                "04004",
                "04070",
                "04093",
                "04046",
                "04006",
                "04042",
                "04106",
                "04094",
                "04098",
                "04043",
                "04014",
                "04002",
                "04107",
                "04102",
                "04092",
                "04038",
                "04030",
                "04101",
                "04112",
                "04116",
                "04122",
                "04104",
                "04124",
                "04123",
                "04103",
                "04082",
                "04087",
                "04109",
                "04061",
                "04108",
                "04073",
                "04090",
                "04084",
                "04105",
                "04085",
                "04062",
                "04049",
                "04083",
                "04050",
                "04076",
                "04048",
                "04054",
                "04009",
                "04022",
                "04057",
                "04040",
                "04055",
                "04037",
                "04010",
                "04029",
                "04016",
                "04088",
                "04041",
                "04267",
                "04015",
                "04270",
                "04051",
                "04091",
                "04024",
                "04291",
                "03813",
                "04071",
                "04268",
                "04077",
                "04068",
                "03860",
                "04231",
                "03832",
                "04256",
                "04274",
                "03847",
                "04020",
                "03849",
                "04085",
                "04281",
                "03845",
                "04271",
                "04255",
              ],
            ],
          },
        ],
      }),
    },
  ],
  ProcessingStep: [
    {
      audience: () => ({ connect: { id: seed_data["Audience"][3]["id"] } }),
      outputType: () => ({ connect: { id: seed_data.DataType[1].id } }),
      sort: 0,
      customCoding: JSONify({
        request: {
          dateStart: { date_add: [{ now: [] }, -6, "month"] },
          dateEnd: { date_add: [{ now: [] }, -2, "days"] },
        },
      }),
    },
    {
      audience: () => ({ connect: { id: seed_data["Audience"][3]["id"] } }),
      outputType: () => ({ connect: { id: seed_data.DataType[0].id } }),
      sort: 1,
      customCoding: JSONify({
        filter: {
          and: [
            {
              in: [
                { var: "zipCode" },
                [
                  "30004",
                  "30005",
                  "30009",
                  "30022",
                  "30024",
                  "30030",
                  "30040",
                  "30041",
                  "30062",
                  "30066",
                  "30067",
                  "30068",
                  "30075",
                  "30076",
                  "30092",
                  "30097",
                  "30269",
                  "30305",
                  "30306",
                  "30307",
                  "30308",
                  "30309",
                  "30319",
                  "30327",
                  "30328",
                  "30338",
                  "30339",
                  "30342",
                  "30345",
                  "30350",
                  "30363",
                  "35213",
                  "35223",
                  "35242",
                  "35243",
                  "35244",
                  "35406",
                  "28801",
                  "28803",
                  "28804",
                  "28805",
                  "28806",
                  "29607",
                  "29609",
                  "29642",
                  "29644",
                  "29650",
                  "29651",
                  "29687",
                  "29690",
                  "31901",
                  "31902",
                  "31903",
                  "31904",
                  "31906",
                  "31907",
                  "31908",
                  "31909",
                  "31914",
                  "31917",
                  "31993",
                  "31997",
                  "31998",
                ],
              ],
            },
          ],
        },
      }),
    },
    {
      audience: () => ({ connect: { id: seed_data["Audience"][3]["id"] } }),
      outputType: () => ({ connect: { id: seed_data.DataType[1].id } }),
      sort: 2,
      customCoding: JSONify({
        demographics: {
          filter: {
            and: [{ ">=": [{ var: "estimatedHomeValue" }, 600000] }],
          },
        },
      }),
    },
    {
      audience: () => ({ connect: { id: seed_data["Audience"][4]["id"] } }),
      outputType: () => ({ connect: { id: seed_data.DataType[2].id } }),
      sort: 0,
      customCoding: JSONify({
        request: {
          dateStart: { date_add: [{ now: [] }, -6, "month"] },
          dateEnd: { date_add: [{ now: [] }, -2, "days"] },
        },
      }),
    },
    {
      audience: () => ({ connect: { id: seed_data["Audience"][4]["id"] } }),
      outputType: () => ({ connect: { id: seed_data.DataType[1].id } }),
      sort: 1,
      customCoding: JSONify({
        observation: {
          filter: {
            and: [{ "<": [{ reduce: { filter: [] } }, 20] }],
          },
        },
      }),
    },
    {
      audience: () => ({ connect: { id: seed_data["Audience"][5]["id"] } }),
      outputType: () => ({ connect: { id: seed_data.DataType[1].id } }),
      sort: 0,
      customCoding: JSONify({
        request: {
          dateStart: { date_add: [{ now: [] }, -6, "month"] },
          dateEnd: { date_add: [{ now: [] }, -2, "days"] },
        },
        demographics: {
          filter: {
            and: [
              { "==": [{ var: "Home Owner" }, true] },
              { "==": [{ var: "Gourmet Cooking" }, true] },
              { "==": [{ var: "Home Furnishings" }, true] },
              { "==": [{ var: "Home Gardening" }, true] },
              { "==": [{ var: "Home Improvement" }, true] },
              { ">": [{ var: "Financial" }, 100000] },
            ],
          },
        },
      }),
    },
  ],
};

export default seed_data